<?php

class Creare_GoogleShops_Model_System_Config_Source_Language {
	public function toOptionArray()
	  {
		return array(
			array('label' => 'Afghanistan', 'value' => 'AF'),
			array('label' => 'Abkhazian', 'value' => 'ab'),
			array('label' => 'Afar', 'value' => 'aa'),
			array('label' => 'Afrikaans', 'value' => 'af'),
			array('label' => 'Albanian', 'value' => 'sq'),
			array('label' => 'Amharic', 'value' => 'am'),
			array('label' => 'Arabic', 'value' => 'ar'),
			array('label' => 'Aragonese', 'value' => 'an'),
			array('label' => 'Armenian', 'value' => 'hy'),
			array('label' => 'Assamese', 'value' => 'as'),
			array('label' => 'Aymara', 'value' => 'ay'),
			array('label' => 'Azerbaijani', 'value' => 'az'),
			array('label' => 'Bashkir', 'value' => 'ba'),
			array('label' => 'Basque', 'value' => 'eu'),
			array('label' => 'Bengali (Bangla)', 'value' => 'bn'),
			array('label' => 'Bhutani', 'value' => 'dz'),
			array('label' => 'Bihari', 'value' => 'bh'),
			array('label' => 'Bislama', 'value' => 'bi'),
			array('label' => 'Breton', 'value' => 'br'),
			array('label' => 'Bulgarian', 'value' => 'bg'),
			array('label' => 'Burmese', 'value' => 'my'),
			array('label' => 'Byelorussian (Belarusian)', 'value' => 'be'),
			array('label' => 'Cambodian', 'value' => 'km'),
			array('label' => 'Catalan', 'value' => 'ca'),
			array('label' => 'Chinese', 'value' => 'zh'),
			array('label' => 'Chinese (Simplified)', 'value' => 'zh-Hans'),
			array('label' => 'Chinese (Traditional)', 'value' => 'zh-Hant'),
			array('label' => 'Corsican', 'value' => 'co'),
			array('label' => 'Croatian', 'value' => 'hr'),
			array('label' => 'Czech', 'value' => 'cs'),
			array('label' => 'Danish', 'value' => 'da'),
			array('label' => 'Dutch', 'value' => 'nl'),
			array('label' => 'English', 'value' => 'en'),
			array('label' => 'Esperanto', 'value' => 'eo'),
			array('label' => 'Estonian', 'value' => 'et'),
			array('label' => 'Faeroese', 'value' => 'fo'),
			array('label' => 'Farsi', 'value' => 'fa'),
			array('label' => 'Fiji', 'value' => 'fj'),
			array('label' => 'Finnish', 'value' => 'fi'),
			array('label' => 'French', 'value' => 'fr'),
			array('label' => 'Frisian', 'value' => 'fy'),
			array('label' => 'Galician', 'value' => 'gl'),
			array('label' => 'Gaelic (Scottish)', 'value' => 'gd'),
			array('label' => 'Gaelic (Manx)', 'value' => 'gv'),
			array('label' => 'Georgian', 'value' => 'ka'),
			array('label' => 'German', 'value' => 'de'),
			array('label' => 'Greek', 'value' => 'el'),
			array('label' => 'Greenlandic', 'value' => 'kl'),
			array('label' => 'Guarani', 'value' => 'gn'),
			array('label' => 'Gujarati', 'value' => 'gu'),
			array('label' => 'Haitian Creole', 'value' => 'ht'),
			array('label' => 'Hausa', 'value' => 'ha'),
			array('label' => 'Hebrew', 'value' => 'he'),
			array('label' => 'Hindi', 'value' => 'hi'),
			array('label' => 'Hungarian', 'value' => 'hu'),
			array('label' => 'Icelandic', 'value' => 'is'),
			array('label' => 'Ido', 'value' => 'io'),
			array('label' => 'Indonesian', 'value' => 'id'),
			array('label' => 'Interlingua', 'value' => 'ia'),
			array('label' => 'Interlingue', 'value' => 'ie'),
			array('label' => 'Inuktitut', 'value' => 'iu'),
			array('label' => 'Inupiak', 'value' => 'ik'),
			array('label' => 'Irish', 'value' => 'ga'),
			array('label' => 'Italian', 'value' => 'it'),
			array('label' => 'Japanese', 'value' => 'ja'),
			array('label' => 'Javanese', 'value' => 'jv'),
			array('label' => 'Kannada', 'value' => 'kn'),
			array('label' => 'Kashmiri', 'value' => 'ks'),
			array('label' => 'Kazakh', 'value' => 'kk'),
			array('label' => 'Kinyarwanda (Ruanda)', 'value' => 'rw'),
			array('label' => 'Kirghiz', 'value' => 'ky'),
			array('label' => 'Kirundi (Rundi)', 'value' => 'rn'),
			array('label' => 'Korean', 'value' => 'ko'),
			array('label' => 'Kurdish', 'value' => 'ku'),
			array('label' => 'Laothian', 'value' => 'lo'),
			array('label' => 'Latin', 'value' => 'la'),
			array('label' => 'Latvian (Lettish)', 'value' => 'lv'),
			array('label' => 'Limburgish ( Limburger)', 'value' => 'li'),
			array('label' => 'Lingala', 'value' => 'ln'),
			array('label' => 'Lithuanian', 'value' => 'lt'),
			array('label' => 'Macedonian', 'value' => 'mk'),
			array('label' => 'Malagasy', 'value' => 'mg'),
			array('label' => 'Malay', 'value' => 'ms'),
			array('label' => 'Malayalam', 'value' => 'ml'),
			array('label' => 'Maltese', 'value' => 'mt'),
			array('label' => 'Maori', 'value' => 'mi'),
			array('label' => 'Marathi', 'value' => 'mr'),
			array('label' => 'Moldavian', 'value' => 'mo'),
			array('label' => 'Mongolian', 'value' => 'mn'),
			array('label' => 'Nauru', 'value' => 'na'),
			array('label' => 'Nepali', 'value' => 'ne'),
			array('label' => 'Norwegian', 'value' => 'no'),
			array('label' => 'Occitan', 'value' => 'oc'),
			array('label' => 'Oriya', 'value' => 'or'),
			array('label' => 'Oromo (Afaan Oromo)', 'value' => 'om'),
			array('label' => 'Pashto (Pushto)', 'value' => 'ps'),
			array('label' => 'Polish', 'value' => 'pl'),
			array('label' => 'Portuguese', 'value' => 'pt'),
			array('label' => 'Punjabi', 'value' => 'pa'),
			array('label' => 'Quechua', 'value' => 'qu'),
			array('label' => 'Rhaeto-Romance', 'value' => 'rm'),
			array('label' => 'Romanian', 'value' => 'ro'),
			array('label' => 'Russian', 'value' => 'ru'),
			array('label' => 'Samoan', 'value' => 'sm'),
			array('label' => 'Sangro', 'value' => 'sg'),
			array('label' => 'Sanskrit', 'value' => 'sa'),
			array('label' => 'Serbian', 'value' => 'sr'),
			array('label' => 'Serbo-Croatian', 'value' => 'sh'),
			array('label' => 'Sesotho', 'value' => 'st'),
			array('label' => 'Setswana', 'value' => 'tn'),
			array('label' => 'Shona', 'value' => 'sn'),
			array('label' => 'Sichuan Yi', 'value' => 'ii'),
			array('label' => 'Sindhi', 'value' => 'sd'),
			array('label' => 'Sinhalese', 'value' => 'si'),
			array('label' => 'Siswati', 'value' => 'ss'),
			array('label' => 'Slovak', 'value' => 'sk'),
			array('label' => 'Slovenian', 'value' => 'sl'),
			array('label' => 'Somali', 'value' => 'so'),
			array('label' => 'Spanish', 'value' => 'es'),
			array('label' => 'Sundanese', 'value' => 'su'),
			array('label' => 'Swahili (Kiswahili)', 'value' => 'sw'),
			array('label' => 'Swedish', 'value' => 'sv'),
			array('label' => 'Tagalog', 'value' => 'tl'),
			array('label' => 'Tajik', 'value' => 'tg'),
			array('label' => 'Tamil', 'value' => 'ta'),
			array('label' => 'Tatar', 'value' => 'tt'),
			array('label' => 'Telugu', 'value' => 'te'),
			array('label' => 'Thai', 'value' => 'th'),
			array('label' => 'Tibetan', 'value' => 'bo'),
			array('label' => 'Tigrinya', 'value' => 'ti'),
			array('label' => 'Tonga', 'value' => 'to'),
			array('label' => 'Tsonga', 'value' => 'ts'),
			array('label' => 'Turkish', 'value' => 'tr'),
			array('label' => 'Turkmen', 'value' => 'tk'),
			array('label' => 'Twi', 'value' => 'tw'),
			array('label' => 'Uighur', 'value' => 'ug'),
			array('label' => 'Ukrainian', 'value' => 'uk'),
			array('label' => 'Urdu', 'value' => 'ur'),
			array('label' => 'Uzbek', 'value' => 'uz'),
			array('label' => 'Vietnamese', 'value' => 'vi'),
			array('label' => 'Volapük', 'value' => 'vo'),
			array('label' => 'Wallon', 'value' => 'wa'),
			array('label' => 'Welsh', 'value' => 'cy'),
			array('label' => 'Wolof', 'value' => 'wo'),
			array('label' => 'Xhosa', 'value' => 'xh'),
			array('label' => 'Yiddish', 'value' => 'yi'),
			array('label' => 'Yoruba', 'value' => 'yo'),
			array('label' => 'Zulu', 'value' => 'zu'),
		);
	}
}