<?php 
$_conf = Mage::helper('googleshops');
if($this->isEnabled()){ ?>
<!-- BEGIN: Google Certified Shops -->
<script type="text/javascript">
	var gts = gts || [];
	gts.push(["id", "<?php echo $_conf->getShopId(); ?>"]);
	<?php
	if($_conf->getBadgePosition() == 'BOTTOM_RIGHT') {
		$position = 'BOTTOM_RIGHT';
	 } else { 
		$position = 'USER_DEFINED';
		switch($_conf->getBadgePosition()) {
			case "TOP_RIGHT":
				$badge_container = 'gts_top_right';
				break;
			case "TOP_LEFT":
				$badge_container = 'gts_top_left';
				break;
			case "BOTTOM_LEFT":
				$badge_container = 'gts_bottom_left';
				break;
			default:
				$position = 'BOTTOM_RIGHT';
				break;
		}
	}	?>
	gts.push(["badge_position", "<?php echo $position; ?>"]);
	<?php if($position == 'USER_DEFINED') { ?>
	gts.push(["badge_container", "<?php echo $badge_container; ?>"]);
	<?php } ?>
	gts.push(["locale", "<?php echo $_conf->getLocale(); ?>"]);
	gts.push(["google_base_subaccount_id", "<?php echo $_conf->getGoogleShoppingAccountId(); ?>"]);
	gts.push(["google_base_country", "<?php echo $_conf->getGoogleShoppingCountry(); ?>"]);
	gts.push(["google_base_language", "<?php echo $_conf->getGoogleShoppingLanguage(); ?>"]);
	
	(function() {
		var gts = document.createElement("script");
		gts.type = "text/javascript";
		gts.async = true;
		gts.src = "https://www.googlecommerce.com/trustedstores/api/js";
		var s = document.getElementsByTagName("script")[0];
		s.parentNode.insertBefore(gts, s);
	})();
</script>
<div id="<?php echo $badge_container; ?>"></div>
<!-- END: Google Certified Shops -->
<?php } ?>